#pragma once

namespace Piero {
enum StatusCode {
    LOGIN_SUCCESS = 0,
    LOGIN_FAILED_USER_NOT_EXIST = 1,
    LOGOUT_FAILED_PASSWORD = 2,
    LOGIN_FAILED_USER_ALREADY_LOGIN = 50,
    LOGOUT_SUCCESS = 3,
    RECEIVE_MESSAGE_SUCCESS = 4,
    // SEND_MESSAGE_SUCCESS = 4,
    SEND_MESSAGE_FAILED = 5,

    GET_USERS_ONLINE_SUCCESS = 8,

    GET_OR_CREATE_CONVERSATION_OF_TWO_USER_SUCCSESS = 9,
    
    GET_CONVERSATION_SUCCSESS = 20,
    CREATE_CONVERSATION_SUCCSESS = 21,

    SEND_INVITATION_TO_JOIN_CONVERSATION_SUCCSESS = 22,
    ACCEPT_JOIN_IN_CONVERSATION_SUCCSESS = 23,
    LEFT_GROUP_CHAT_SUCCSESS = 24
};

}